export const labels = ['Nome', 'Preco', 'Descricao', 'Tamanho', 'Genero', 'Cor', 'Colecao', 'Categoria', 'Marca', 'Utilizador']
export const produtosList = [
  {
    id: 1,
    nome: 'CAPACETE NEXX SX100R ABISAL BLACK RED MATT',
    preco: '186,30 €',
    descricao: 'Capacete Nexx SX.100R Abisal Preto / Vermelho Mate. Capacete integral em material termoplástico muito leve. Destaca-se por oferecer um design aerodinâmico, moderno e esportivo ideal para o uso diário. Tem uma pala de sol integrada, um sistema de ventilação eficaz e um forro interior muito confortável. Destaca-se o spoiler traseiro projetado para oferecer excelente desempenho aerodinâmico.',
    tamanho: 'S',
    genero: 'Feminino',
    cor: 'Cizento',
    colecao: 'Anual',
    categoria: 'capacetes',
    marca: 'Nexx',
    utilizador: 'Ana',
    images: './1-1.jpg'
  },
  {
    id: 2,
    nome: 'Produto 2',
    preco: '19,99 €',
    descricao: 'Descrição 2',
    tamanho: 'L',
    genero: 'Feminino',
    cor: 'Azul',
    colecao: 'Coleção 2',
    categoria: 'Category 2',
    marca: 'Marca 2',
    utilizador: 'Utilizador 2',
  },
  {
    id: 3,
    nome: 'Produto 3',
    preco: '14,99 €',
    descricao: 'Descrição 3',
    tamanho: 'M',
    genero: 'Masculino',
    cor: 'Verde',
    colecao: 'Coleção 3',
    categoria: 'Category 3',
    marca: 'Marca 3',
    utilizador: 'Utilizador 3',
  },
]